set -a terminal-features "tmux-256color:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""

# fast esc resp time in nvim
set -sg escape-time 0

# Make copy mode copy to system clipboard (in this case im using x11 so use xclip)
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"

# New window/pane to go to current pane path
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

